-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 10:47:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema material_et_medical_bdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema material_et_medical_bdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `material_et_medical_bdd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `material_et_medical_bdd` ;

-- -----------------------------------------------------
-- Table `material_et_medical_bdd`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `material_et_medical_bdd`.`categorie` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `material_et_medical_bdd`.`materiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `material_et_medical_bdd`.`materiel` (
  `id` INT NOT NULL,
  `reference` VARCHAR(45) NOT NULL,
  `designation` VARCHAR(45) NULL,
  `date_achat` DATETIME NULL,
  `prix_jour` FLOAT NULL,
  `categorie` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materiel_categorie_idx` (`categorie` ASC) VISIBLE,
  CONSTRAINT `fk_materiel_categorie`
    FOREIGN KEY (`categorie`)
    REFERENCES `material_et_medical_bdd`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `material_et_medical_bdd`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `material_et_medical_bdd`.`type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `material_et_medical_bdd`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `material_et_medical_bdd`.`client` (
  `id` INT NOT NULL,
  `code_client` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_type1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `material_et_medical_bdd`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `material_et_medical_bdd`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `material_et_medical_bdd`.`location` (
  `id` INT NOT NULL,
  `duree` INT NULL,
  `client_id` INT NOT NULL,
  `materiel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_location_materiel1_idx` (`materiel_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `material_et_medical_bdd`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_materiel1`
    FOREIGN KEY (`materiel_id`)
    REFERENCES `material_et_medical_bdd`.`materiel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `material_et_medical_bdd`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `material_et_medical_bdd`.`adresse` (
  `id` INT NOT NULL,
  `numero` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `code_postal` INT NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adresse_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_adresse_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `material_et_medical_bdd`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
